apiVersion : apps/v1
kind: Deployment
metadata:
  name: qbrayanfooddetection 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbrayanfooddetection 
  template:
    metadata:
      labels:
        app: qbrayanfooddetection 
    spec:
      containers:
        - name: qbrayanfooddetection 
          image: foodcontainerregistry.azurecr.io/qbrayanfooddetection
          ports:
          - containerPort: 80
